// templates.js — 34 Professional CV Templates
const CV_TEMPLATES = [
  // ===== 1–4: Original Templates =====
  { id: 'modern', name: 'Modern', group: 'Popular',
    headerBg: 'linear-gradient(135deg, #4f46e5, #7c3aed)', headerColor: '#fff',
    titleColor: '#4f46e5', titleBorder: 'bottom', titleBorderColor: '#4f46e5',
    bodyFont: "'Inter', sans-serif", headerFont: "'Inter', sans-serif",
    skillBg: 'rgba(79,70,229,0.1)', skillColor: '#4f46e5', skillBorder: 'none' },

  { id: 'classic', name: 'Classic', group: 'Popular',
    headerBg: '#fff', headerColor: '#1f2937', headerAlign: 'center',
    titleColor: '#1f2937', titleBorder: 'bottom', titleBorderColor: '#d1d5db',
    bodyFont: "'Source Sans Pro', sans-serif", headerFont: "'Playfair Display', serif",
    skillBg: 'transparent', skillColor: '#374151', skillBorder: '1px solid #d1d5db',
    headerBottomBorder: '3px solid #1f2937' },

  { id: 'developer', name: 'Developer', group: 'Tech',
    headerBg: '#0f172a', headerColor: '#e2e8f0',
    titleColor: '#38bdf8', titleBorder: 'left', titleBorderColor: '#38bdf8',
    bodyFont: "'Roboto', sans-serif", headerFont: "'Roboto', sans-serif",
    skillBg: '#1e293b', skillColor: '#38bdf8', skillBorder: '1px solid #334155',
    nameColor: '#38bdf8' },

  { id: 'executive', name: 'Executive', group: 'Corporate',
    headerBg: 'linear-gradient(135deg, #1e3a5f, #2d5a87)', headerColor: '#fff',
    titleColor: '#1e3a5f', titleBorder: 'bottom', titleBorderColor: '#c9a84c',
    bodyFont: "'Source Sans Pro', sans-serif", headerFont: "'Lora', serif",
    skillBg: 'rgba(30,58,95,0.08)', skillColor: '#1e3a5f', skillBorder: 'none',
    headerAccentBar: 'linear-gradient(90deg, #c9a84c, #e8c860, #c9a84c)' },

  // ===== 5–10: Minimalist & Clean =====
  { id: 'minimalist', name: 'Minimalist', group: 'Clean',
    headerBg: '#fff', headerColor: '#111827', headerAlign: 'left',
    titleColor: '#111827', titleBorder: 'bottom', titleBorderColor: '#e5e7eb',
    bodyFont: "'Inter', sans-serif", headerFont: "'Inter', sans-serif",
    skillBg: '#f3f4f6', skillColor: '#374151', skillBorder: 'none',
    headerBottomBorder: '1px solid #e5e7eb' },

  { id: 'clean-mono', name: 'Clean Mono', group: 'Clean',
    headerBg: '#fafafa', headerColor: '#18181b',
    titleColor: '#18181b', titleBorder: 'bottom', titleBorderColor: '#18181b',
    bodyFont: "'Inter', sans-serif", headerFont: "'Inter', sans-serif",
    skillBg: 'transparent', skillColor: '#18181b', skillBorder: '1px solid #d4d4d8',
    headerBottomBorder: '2px solid #18181b' },

  { id: 'swiss', name: 'Swiss Design', group: 'Clean',
    headerBg: '#fff', headerColor: '#000', headerAlign: 'left',
    titleColor: '#dc2626', titleBorder: 'none', titleBorderColor: 'none',
    bodyFont: "'Roboto', sans-serif", headerFont: "'Roboto', sans-serif",
    skillBg: '#fee2e2', skillColor: '#dc2626', skillBorder: 'none',
    headerBottomBorder: '4px solid #dc2626', nameColor: '#000' },

  { id: 'airy', name: 'Airy', group: 'Clean',
    headerBg: '#fff', headerColor: '#334155',
    titleColor: '#64748b', titleBorder: 'bottom', titleBorderColor: '#e2e8f0',
    bodyFont: "'Inter', sans-serif", headerFont: "'Inter', sans-serif",
    skillBg: '#f1f5f9', skillColor: '#475569', skillBorder: 'none',
    headerBottomBorder: '1px solid #e2e8f0' },

  { id: 'paper', name: 'Paper White', group: 'Clean',
    headerBg: '#fff', headerColor: '#1a1a1a', headerAlign: 'center',
    titleColor: '#555', titleBorder: 'bottom', titleBorderColor: '#ccc',
    bodyFont: "'Lora', serif", headerFont: "'Lora', serif",
    skillBg: 'transparent', skillColor: '#333', skillBorder: '1px solid #ddd' },

  { id: 'sharp', name: 'Sharp Edge', group: 'Clean',
    headerBg: '#111827', headerColor: '#f9fafb',
    titleColor: '#111827', titleBorder: 'bottom', titleBorderColor: '#111827',
    bodyFont: "'Inter', sans-serif", headerFont: "'Inter', sans-serif",
    skillBg: '#111827', skillColor: '#fff', skillBorder: 'none' },

  // ===== 11–16: Colorful & Creative =====
  { id: 'ocean', name: 'Ocean Blue', group: 'Colorful',
    headerBg: 'linear-gradient(135deg, #0ea5e9, #2563eb)', headerColor: '#fff',
    titleColor: '#0369a1', titleBorder: 'bottom', titleBorderColor: '#0ea5e9',
    bodyFont: "'Inter', sans-serif", headerFont: "'Inter', sans-serif",
    skillBg: 'rgba(14,165,233,0.1)', skillColor: '#0369a1', skillBorder: 'none' },

  { id: 'emerald', name: 'Emerald Green', group: 'Colorful',
    headerBg: 'linear-gradient(135deg, #059669, #10b981)', headerColor: '#fff',
    titleColor: '#047857', titleBorder: 'left', titleBorderColor: '#10b981',
    bodyFont: "'Inter', sans-serif", headerFont: "'Inter', sans-serif",
    skillBg: 'rgba(16,185,129,0.1)', skillColor: '#047857', skillBorder: 'none' },

  { id: 'sunset', name: 'Sunset Orange', group: 'Colorful',
    headerBg: 'linear-gradient(135deg, #ea580c, #f97316)', headerColor: '#fff',
    titleColor: '#c2410c', titleBorder: 'bottom', titleBorderColor: '#f97316',
    bodyFont: "'Source Sans Pro', sans-serif", headerFont: "'Source Sans Pro', sans-serif",
    skillBg: 'rgba(249,115,22,0.1)', skillColor: '#c2410c', skillBorder: 'none' },

  { id: 'rose', name: 'Rose Pink', group: 'Colorful',
    headerBg: 'linear-gradient(135deg, #e11d48, #f43f5e)', headerColor: '#fff',
    titleColor: '#be123c', titleBorder: 'bottom', titleBorderColor: '#f43f5e',
    bodyFont: "'Inter', sans-serif", headerFont: "'Playfair Display', serif",
    skillBg: 'rgba(244,63,94,0.08)', skillColor: '#be123c', skillBorder: 'none' },

  { id: 'lavender', name: 'Lavender', group: 'Colorful',
    headerBg: 'linear-gradient(135deg, #7c3aed, #a78bfa)', headerColor: '#fff',
    titleColor: '#6d28d9', titleBorder: 'bottom', titleBorderColor: '#a78bfa',
    bodyFont: "'Inter', sans-serif", headerFont: "'Inter', sans-serif",
    skillBg: 'rgba(167,139,250,0.1)', skillColor: '#6d28d9', skillBorder: 'none' },

  { id: 'teal', name: 'Teal', group: 'Colorful',
    headerBg: 'linear-gradient(135deg, #0d9488, #14b8a6)', headerColor: '#fff',
    titleColor: '#0f766e', titleBorder: 'left', titleBorderColor: '#14b8a6',
    bodyFont: "'Roboto', sans-serif", headerFont: "'Roboto', sans-serif",
    skillBg: 'rgba(20,184,166,0.1)', skillColor: '#0f766e', skillBorder: 'none' },

  // ===== 17–22: Corporate & Business =====
  { id: 'corporate', name: 'Corporate Blue', group: 'Corporate',
    headerBg: '#1e40af', headerColor: '#fff',
    titleColor: '#1e40af', titleBorder: 'bottom', titleBorderColor: '#1e40af',
    bodyFont: "'Source Sans Pro', sans-serif", headerFont: "'Source Sans Pro', sans-serif",
    skillBg: 'rgba(30,64,175,0.08)', skillColor: '#1e40af', skillBorder: 'none' },

  { id: 'banking', name: 'Banking', group: 'Corporate',
    headerBg: '#1a1a2e', headerColor: '#e0c97f',
    titleColor: '#1a1a2e', titleBorder: 'bottom', titleBorderColor: '#d4a843',
    bodyFont: "'Source Sans Pro', sans-serif", headerFont: "'Playfair Display', serif",
    skillBg: 'rgba(26,26,46,0.06)', skillColor: '#1a1a2e', skillBorder: 'none',
    nameColor: '#e0c97f' },

  { id: 'consulting', name: 'Consulting', group: 'Corporate',
    headerBg: 'linear-gradient(135deg, #374151, #4b5563)', headerColor: '#fff',
    titleColor: '#374151', titleBorder: 'bottom', titleBorderColor: '#9ca3af',
    bodyFont: "'Inter', sans-serif", headerFont: "'Inter', sans-serif",
    skillBg: '#f3f4f6', skillColor: '#374151', skillBorder: 'none' },

  { id: 'legal', name: 'Legal', group: 'Corporate',
    headerBg: '#fff', headerColor: '#1c1917', headerAlign: 'center',
    titleColor: '#78350f', titleBorder: 'bottom', titleBorderColor: '#92400e',
    bodyFont: "'Lora', serif", headerFont: "'Playfair Display', serif",
    skillBg: 'transparent', skillColor: '#78350f', skillBorder: '1px solid #d6d3d1',
    headerBottomBorder: '3px double #78350f' },

  { id: 'finance', name: 'Finance', group: 'Corporate',
    headerBg: 'linear-gradient(135deg, #064e3b, #065f46)', headerColor: '#d1fae5',
    titleColor: '#064e3b', titleBorder: 'bottom', titleBorderColor: '#059669',
    bodyFont: "'Source Sans Pro', sans-serif", headerFont: "'Source Sans Pro', sans-serif",
    skillBg: 'rgba(6,78,59,0.06)', skillColor: '#064e3b', skillBorder: 'none' },

  { id: 'hr', name: 'HR Professional', group: 'Corporate',
    headerBg: 'linear-gradient(135deg, #7e22ce, #9333ea)', headerColor: '#fff',
    titleColor: '#7e22ce', titleBorder: 'left', titleBorderColor: '#9333ea',
    bodyFont: "'Inter', sans-serif", headerFont: "'Inter', sans-serif",
    skillBg: 'rgba(147,51,234,0.08)', skillColor: '#7e22ce', skillBorder: 'none' },

  // ===== 23–28: Industry Specific =====
  { id: 'medical', name: 'Medical', group: 'Industry',
    headerBg: 'linear-gradient(135deg, #0891b2, #06b6d4)', headerColor: '#fff',
    titleColor: '#0e7490', titleBorder: 'bottom', titleBorderColor: '#06b6d4',
    bodyFont: "'Roboto', sans-serif", headerFont: "'Roboto', sans-serif",
    skillBg: 'rgba(6,182,212,0.08)', skillColor: '#0e7490', skillBorder: 'none' },

  { id: 'engineering', name: 'Engineering', group: 'Industry',
    headerBg: '#292524', headerColor: '#fafaf9',
    titleColor: '#f59e0b', titleBorder: 'left', titleBorderColor: '#f59e0b',
    bodyFont: "'Roboto', sans-serif", headerFont: "'Roboto', sans-serif",
    skillBg: '#fef3c7', skillColor: '#92400e', skillBorder: 'none',
    nameColor: '#fbbf24' },

  { id: 'marketing', name: 'Marketing', group: 'Industry',
    headerBg: 'linear-gradient(135deg, #db2777, #ec4899)', headerColor: '#fff',
    titleColor: '#be185d', titleBorder: 'bottom', titleBorderColor: '#ec4899',
    bodyFont: "'Inter', sans-serif", headerFont: "'Inter', sans-serif",
    skillBg: 'rgba(236,72,153,0.08)', skillColor: '#be185d', skillBorder: 'none' },

  { id: 'academic', name: 'Academic', group: 'Industry',
    headerBg: '#fff', headerColor: '#1e293b', headerAlign: 'center',
    titleColor: '#1e3a5f', titleBorder: 'bottom', titleBorderColor: '#94a3b8',
    bodyFont: "'Lora', serif", headerFont: "'Lora', serif",
    skillBg: 'transparent', skillColor: '#334155', skillBorder: '1px solid #cbd5e1',
    headerBottomBorder: '2px solid #1e3a5f' },

  { id: 'startup', name: 'Startup', group: 'Industry',
    headerBg: 'linear-gradient(135deg, #4f46e5, #06b6d4)', headerColor: '#fff',
    titleColor: '#4f46e5', titleBorder: 'left', titleBorderColor: '#06b6d4',
    bodyFont: "'Inter', sans-serif", headerFont: "'Inter', sans-serif",
    skillBg: 'rgba(79,70,229,0.06)', skillColor: '#4338ca', skillBorder: 'none' },

  { id: 'teacher', name: 'Teacher', group: 'Industry',
    headerBg: 'linear-gradient(135deg, #16a34a, #22c55e)', headerColor: '#fff',
    titleColor: '#15803d', titleBorder: 'bottom', titleBorderColor: '#22c55e',
    bodyFont: "'Source Sans Pro', sans-serif", headerFont: "'Source Sans Pro', sans-serif",
    skillBg: 'rgba(34,197,94,0.08)', skillColor: '#15803d', skillBorder: 'none' },

  // ===== 29–34: Premium & Special =====
  { id: 'luxury', name: 'Luxury Gold', group: 'Premium',
    headerBg: '#0c0c0c', headerColor: '#d4af37',
    titleColor: '#0c0c0c', titleBorder: 'bottom', titleBorderColor: '#d4af37',
    bodyFont: "'Playfair Display', serif", headerFont: "'Playfair Display', serif",
    skillBg: 'rgba(212,175,55,0.08)', skillColor: '#0c0c0c', skillBorder: '1px solid #d4af37',
    nameColor: '#d4af37', headerAccentBar: 'linear-gradient(90deg, #d4af37, #f0d060, #d4af37)' },

  { id: 'dark-pro', name: 'Dark Pro', group: 'Premium',
    headerBg: '#18181b', headerColor: '#fafafa',
    titleColor: '#a1a1aa', titleBorder: 'left', titleBorderColor: '#6366f1',
    bodyFont: "'Inter', sans-serif", headerFont: "'Inter', sans-serif",
    skillBg: '#27272a', skillColor: '#a1a1aa', skillBorder: 'none',
    nameColor: '#fff', paperBg: '#f4f4f5' },

  { id: 'gradient-pro', name: 'Gradient Pro', group: 'Premium',
    headerBg: 'linear-gradient(135deg, #667eea, #764ba2)', headerColor: '#fff',
    titleColor: '#5b21b6', titleBorder: 'bottom', titleBorderColor: '#8b5cf6',
    bodyFont: "'Inter', sans-serif", headerFont: "'Inter', sans-serif",
    skillBg: 'rgba(139,92,246,0.08)', skillColor: '#5b21b6', skillBorder: 'none' },

  { id: 'elegant-serif', name: 'Elegant Serif', group: 'Premium',
    headerBg: '#fff', headerColor: '#1f2937', headerAlign: 'center',
    titleColor: '#4a1942', titleBorder: 'bottom', titleBorderColor: '#4a1942',
    bodyFont: "'Lora', serif", headerFont: "'Playfair Display', serif",
    skillBg: 'transparent', skillColor: '#4a1942', skillBorder: '1px solid #4a1942',
    headerBottomBorder: '2px solid #4a1942' },

  { id: 'neon-tech', name: 'Neon Tech', group: 'Premium',
    headerBg: '#0a0a0a', headerColor: '#22d3ee',
    titleColor: '#06b6d4', titleBorder: 'left', titleBorderColor: '#22d3ee',
    bodyFont: "'Roboto', sans-serif", headerFont: "'Roboto', sans-serif",
    skillBg: 'rgba(34,211,238,0.08)', skillColor: '#06b6d4', skillBorder: '1px solid rgba(34,211,238,0.2)',
    nameColor: '#22d3ee' },

  { id: 'coral', name: 'Coral', group: 'Colorful',
    headerBg: 'linear-gradient(135deg, #f97316, #ef4444)', headerColor: '#fff',
    titleColor: '#ea580c', titleBorder: 'bottom', titleBorderColor: '#f97316',
    bodyFont: "'Inter', sans-serif", headerFont: "'Inter', sans-serif",
    skillBg: 'rgba(249,115,22,0.08)', skillColor: '#ea580c', skillBorder: 'none' },
];
